projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - types/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - types/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: types/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
